#! /bin/sh

#Sourcing the colors
. "${HOME}/.config/bspwm/colors.sh"

#bspc monitor -d Terminal Web Doc Code MPV Spotify Other
#bspc monitor -d $(echo -e '\uf120') $(echo -e '\uf269') $(echo -e '\uf15c') $(echo -e '\uf121') $(echo -e '\uf001') $(echo -e '\uf008') $(echo -e '\uf141')
bspc monitor -d $(echo -e '\uf192') $(echo -e '\uf192') $(echo -e '\uf192') $(echo -e '\uf192') $(echo -e '\uf192') $(echo -e '\uf192') $(echo -e '\uf192')

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width  2
bspc config window_gap    5      

bspc config remove_disabled_monitors          true
bspc config remove_unplugged_monitors         true

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc config pointer_modifier                  mod4
bspc config pointer_action1                   move
bspc config pointer_action2                   resize_side
bspc config pointer_action3                   resize_corner

bspc config normal_frame_opacity 0.9
bspc config focused_frame_opacity 0.5

bspc config external_rules_command            "$HOME/.config/bspwm/rules"
bash /home/mudit/.config/bspwm/bspwm_colors.sh &
